### ISSUE TITLE
为什么我的推理结果，box_objectness*box_cls_score分数非常低，但是pytorch模型推理是正确的

### ISSUE THREAD

**Issue by jxncyym** [gesanqiu/SNPE_Tutorial#20]
为什么我的推理结果，box_objectness*box_cls_score分数非常低，但是pytorch模型推理是正确的，dlc是通过onnx转换为dlc的，转换onnx是参考本repo中的模型转换readme的方式进行转换的

**Comment by gesanqiu** [comment]
只能一层一层对比输出，如果是自训练模型建议查一下grids anchor
