### ISSUE TITLE
SNPE 怎么支持模型多个输入？

### ISSUE THREAD

**Issue by johnbhlm** [gesanqiu/SNPE_Tutorial#21]
SNPE 怎么支持模型多个输入？
例如，输入是 rgb 和 depth 图像， raw_list.txt 需要怎么设置？

**Comment by gesanqiu** [comment]
raw_list.txt正常给就行，但是需要看看snpe-net-run的配置，我印象里有相关配置来实现。代码里是比较好实现的。
