### ISSUE TITLE
使用userbuffer时输入数据如何填充

### ISSUE THREAD

**Issue by zhengshuo1** [gesanqiu/SNPE_Tutorial#3]
您好，我这边现在遇到两个疑惑的地方
1）CreateUserBuffer里，有个获取输入、输出层名字的地方，我现在只分别获取到了一个名字，input，和output，这可能是什么原因呢？
2）我现在不太理解输入数据是如何填充进去的，我以为是填到m_inputTensors["input"]里就可以了，但从结果看这样用似乎不对，填充数据我应该参考哪部分代码呢？

**Comment by Stephenfang51** [comment]
> 您好，我这边现在遇到两个疑惑的地方 1）CreateUserBuffer里，有个获取输入、输出层名字的地方，我现在只分别获取到了一个名字，input，和output，这可能是什么原因呢？ 2）我现在不太理解输入数据是如何填充进去的，我以为是填到m_inputTensors["input"]里就可以了，但从结果看这样用似乎不对，填充数据我应该参考哪部分代码呢？

遇到类似的问题， 没有找到数据是如何进入的
请问你解决了吗？

**Comment by sohan1920** [comment]
I have the same question. I am not able to find the code where the frame data is being filled. Can you please mention the file name and line number of the code?

**Comment by gesanqiu** [comment]
1.具体有几个输入输出层视模型自身而定，可以使用netron查看；
2.CreateUserBuffer申请DMA Buffer，申请到的内存首地址被存在了m_inputTensors和m_outputTensors这两个哈希表中，在PreProcess中我通过getInputTensor()取得地址并直接将图像copy到这块内存。

> 您好，我这边现在遇到两个疑惑的地方 1）CreateUserBuffer里，有个获取输入、输出层名字的地方，我现在只分别获取到了一个名字，input，和output，这可能是什么原因呢？ 2）我现在不太理解输入数据是如何填充进去的，我以为是填到m_inputTensors["input"]里就可以了，但从结果看这样用似乎不对，填充数据我应该参考哪部分代码呢？

**Comment by gesanqiu** [comment]
> I have the same question. I am not able to find the code where the frame data is being filled. Can you please mention the file name and line number of the code?

In ./yolov5s/YOLOv5sImpl.cpp line 80, I create a cv::Mat object with the memory allocate by `CreaterUserBuffer()`, the input image will copy into this cv::Mat.
